@startuml
'https://plantuml.com/activity-diagram-beta

title "简单的活动"
'1：使用(*)作为活动图的开始
'2：使用（*top)可以强制开始点的位置
'3：使用-->绘制箭头
'4: 使用-->(*) 作为活动图的结束
'5：使用""-->(*) 作为指定标签的结束

(*top)-->"sss"

-->"块标签"
-->"块标签2"

'代表整个周期的结束
块标签-->(*)

@enduml
